import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
function Field(p) {
    return (_jsxs("div", { className: "field", children: [_jsx("label", { children: p.label }), _jsx("input", { value: p.value, onChange: (e) => p.on(e.target.value), placeholder: p.placeholder || "" })] }));
}
export default function SettingsModal(p) {
    if (!p.open)
        return null;
    const s = p.keys;
    return (_jsx("div", { className: "modalBack", onMouseDown: p.onClose, children: _jsxs("div", { className: "modal", onMouseDown: (e) => e.stopPropagation(), children: [_jsxs("div", { className: "panelHeader", children: [_jsx("h3", { children: "Station Settings" }), _jsx("span", { children: "Keys saved to LocalStorage (optional push to backend)" })] }), _jsxs("div", { className: "formGrid", children: [_jsx(Field, { label: "OpenAI API Key", value: s.openaiKey, on: (v) => p.onChange({ ...s, openaiKey: v }) }), _jsx(Field, { label: "GitHub Token", value: s.githubToken, on: (v) => p.onChange({ ...s, githubToken: v }) }), _jsx(Field, { label: "TTS Key", value: s.ttsKey, on: (v) => p.onChange({ ...s, ttsKey: v }) }), _jsx(Field, { label: "Webhooks URL", value: s.webhooksUrl, on: (v) => p.onChange({ ...s, webhooksUrl: v }), placeholder: "https://..." }), _jsx(Field, { label: "OCR Key", value: s.ocrKey, on: (v) => p.onChange({ ...s, ocrKey: v }) }), _jsx(Field, { label: "Web Integration Key", value: s.webIntegrationKey, on: (v) => p.onChange({ ...s, webIntegrationKey: v }) }), _jsx(Field, { label: "WhatsApp Key", value: s.whatsappKey, on: (v) => p.onChange({ ...s, whatsappKey: v }) }), _jsx(Field, { label: "Email SMTP (string)", value: s.emailSmtp, on: (v) => p.onChange({ ...s, emailSmtp: v }), placeholder: "smtp://user:pass@host:587" }), _jsx(Field, { label: "GitHub Repo (owner/repo)", value: s.githubRepo, on: (v) => p.onChange({ ...s, githubRepo: v }), placeholder: "owner/repo" }), _jsx(Field, { label: "Render API Key", value: s.renderApiKey, on: (v) => p.onChange({ ...s, renderApiKey: v }) }), _jsx(Field, { label: "Edit Mode Key (required for Ops)", value: s.editModeKey, on: (v) => p.onChange({ ...s, editModeKey: v }), placeholder: "1234" })] }), _jsxs("div", { style: { display: "flex", gap: 10, marginTop: 12, alignItems: "center", justifyContent: "space-between" }, children: [_jsx("div", { style: { color: "rgba(255,255,255,.65)", fontSize: 12 }, children: p.statusText ? p.statusText : "Tip: keep keys local; push only if you want backend to execute ops." }), _jsxs("div", { style: { display: "flex", gap: 8 }, children: [_jsx("button", { className: "btn", onClick: p.onSaveLocal, children: "Save Local" }), _jsx("button", { className: "btn btnPrimary", onClick: p.onPushBackend, disabled: !p.pushEnabled, children: "Save to Backend" }), _jsx("button", { className: "btn btnDanger", onClick: p.onClose, children: "Close" })] })] })] }) }));
}
